---
title: RBW_BetaDiversity
Date: 31.5.21
Correspondance: nathanwilliams22@gmail.com
---

```{r Load Data}
library("phyloseq")
library("vegan")
library("ggplot2")
library("dplyr")
library("ape")
library("tidyverse")
library("tidyr")

setwd("~/Dropbox/UTS/PhD/Projects/Chapter1_Vibrio_latitude_study/Data/16S/Data")
asv_rarefied_long <- read_csv('asv_rarefy30k_long_chloroplasts.csv')
sample_data <- read_csv('SMD.csv')


NathanTheme <- list(   #scale_x_discrete(limits=(locations)),
                       theme(axis.title.x = element_text(vjust = 0, hjust = 0.5, size = 16)),
                       theme(axis.title.y = element_text(vjust = 1, hjust = 0.5, size = 16)),
                       theme(axis.text=element_text(size=10)),
                       theme(axis.text.x = element_text(hjust=1, size = 14, angle = 90)),
                       theme(axis.text.y = element_text(hjust=1, size = 14, angle = 0)),
                       theme(panel.border = element_blank(), panel.grid.major = element_blank(), 
                             panel.background = element_blank(),panel.grid.minor = element_blank(), 
                             axis.line = element_line(colour = 'black')))

source('~/Dropbox/UTS/PhD/Projects/Chapter2_RoseBay/Data_Analysis/Data/16S//Scripts/pairwise.adonis.r')

```

```{r Filter Chloroplasts}
Chloroplasts <- asv_rarefied_long %>% filter(Kingdom == "Eukaryota")

Chloroplasts_bp <- Chloroplasts %>% ggplot(aes(x=Location, y=RA, fill=(Family))) + 
  geom_bar(stat='identity') +
  #scale_fill_manual(values=c(C21)) +
  labs( x= 'Location', y= 'Relative Abundance') +
  NathanTheme
Chloroplasts_bp

```

```{r NMDS Data preparation}
library(tidyverse)
library(vegan)
library(dplyr)
library(reshape2)
Rarefied30K_subset <- asv_rarefy30k_long %>% dplyr::select(ASV_name, Abundance_Vegan_Rarefied, SampleID)
Rarefied30K_subset <- Rarefied30K_subset %>% filter(!Abundance_Vegan_Rarefied ==0)
Rarefied30K.asvs.wide.OFG <- reshape2::dcast(Rarefied30K_subset , SampleID~ASV_name, value.var = "Abundance_Vegan_Rarefied", fill=0)
rownames(Rarefied30K.asvs.wide.OFG) <- Rarefied30K.asvs.wide.OFG$SampleID
Rarefied30K_nmds_df <- Rarefied30K.asvs.wide.OFG [,-c(1)]
```

```{r NMDS}
Rarefied30K.nMDS <- metaMDS(Rarefied30K_nmds_df, distance = "bray", try =99, trymax=100, autotransform = F)
#stressplot(Rarefied30K.nMDS)
#plot(Rarefied30K.nMDS)
names(Rarefied30K.nMDS)
Rarefied30K.nMDS.points <- cbind(Rarefied30K.asvs.wide.OFG[,c(1)], as.data.frame(Rarefied30K.nMDS$points))
colnames(Rarefied30K.nMDS.points)[1] <- "SampleID"
Rarefied30K.nMDS.points <- Rarefied30K.nMDS.points %>% mutate(code=as.character(SampleID)) %>% left_join(sample_data)
Rarefied30K.nMDS.points$mycl450 <- as.character(Rarefied30K.nMDS.points$mycl450)
```

```{r MDS}
library(tidyverse)
MDS.Rarefied30K <- ggplot(Rarefied30K.nMDS.points, aes(x=MDS1, y=MDS2, color = `mycl450`, label = Location)) + 
  geom_point(aes(size=0.4, alpha=0.5)) +
  #geom_text(aes(label = Location),hjust=0, vjust=0) +
  scale_colour_manual(values=c("1"="#d34937", "2"="#49d2ff")) +
  NathanTheme
MDS.Rarefied30K
```

